### ISSUE TITLE
Erstellen einer Wiki-Seite für: Visualization of System Vision + Context

### ISSUE THREAD

**Issue by mkgundelach** [MatthiasWinklerFHSWF/space-SE#4]
### Übersicht

Die Punkte Problem, Solution und Value in der Wiki Seite erläutern

### Akzeptanzkriterien

- [x] Wiki Seite erstellen
- [x] Inhalte eintragen
- [x] Teamreview

**Comment by MatthiasWinklerFHSWF** [comment]
Teamreview abgeschlossen (Leonie, Mika, Matthias) 18:00 Uhr - 11.05.2022
