### ISSUE TITLE
Use Case Diagramme überarbeiten 

### ISSUE THREAD

**Issue by MatthiasWinklerFHSWF** [MatthiasWinklerFHSWF/space-SE#9]
nochmal anhand der Vorlage aus der Vorlesung überarbeiten
vorallem den Standardablauf beschreiben Punktweise. und beim alternativen Flow darauf eingehen

Titelbezeichnung 

Trigger überarbeiten dort reinschreiben wies im System abläuft e.g. Button Menüpunkt 5 anklicken

![image](https://user-images.githubusercontent.com/95693321/169047484-550927f6-32e2-47c5-a5de-6fce905b4097.png)

**Comment by leoniexr** [comment]
super, danke
